package com.android.mihospital.utils;

public class EspecialidadesUtil {
	private static String[] especilidades = {
		"Adolescencia y Pubertad",
		"Alergia e Inmunología",
		"Alergia e Inmunología Infantil",
		"Andrología",
		"Cardiología",
		"Cardiología Infantil",
		"Cirugía Cardiovascular",
		"Cirugía Cardiovascular Infantil",
		"Cirugía de Cabeza y Cuello y Maxilo-Facial",
		"Cirugía de Cabeza y Cuello y Maxilo-Facial Infantil",
		"Cirugía de Mano",
		"Cirugía de Quemados",
		"Cirugía Del Pie",
		"Cirugía Digestiva Endoscópica",
		"Cirugía Estetica",
		"Cirugía General",
		"Cirugía Hepatobiliar Pancreatica",
		"Cirugía Infantil",
		"Cirugía Oncológica",
		"Cirugía Reparadora",
		"Cirugía Torácica",
		"Cirugía Vascular Periferica",
		"Clínica Médica",
		"Dermatología",
		"Dermatología Infantil",
		"Disfunción Sexual",
		"Endocrinología y Metabolismo",
		"Endocrinología y Metabolismo Infantil",
		"Esterilidad",
		"Estomatología",
		"Fisiatría",
		"Flebología",
		"Gastroenterología",
		"Gastroenterología Infantil",
		"Genetica Médica",
		"Geriatría",
		"Ginecología",
		"Ginecología Infanto-Juvenil",
		"Hematología",
		"Hematología Pediátrica",
		"Hemostasia y Trombosis",
		"Hepatología",
		"Infectología",
		"Infectología Infantil",
		"Micología Médica",
		"Nefrología",
		"Nefrología Infantil",
		"Neumonología",
		"Neumonología Infantil",
		"Neurocirugía",
		"Neurocirugía Infantil",
		"Neurofisiología",
		"Neurofisiología Infantil",
		"Neurología",
		"Neurología Infantil",
		"Neurooftalmología",
		"Neurooftalmología Infantil",
		"Nutrición y Diabetología",
		"Nutrición y Diabetología Infanto-Juvenil",
		"Obstetricia",
		"Oftalmología",
		"Oftalmología Infantil",
		"Oncología",
		"Oncología Infantil",
		"Osteopatías Metabólicas",
		"Otorrinolaringología",
		"Otorrinolaringología Infantil",
		"Patología Mamaria",
		"Pediatría",
		"Proctología",
		"Reumatología",
		"Reumatología Infantil",
		"Toxicología",
		"Traumatología y Ortopedia",
		"Traumatología y Ortopedia Infantil",
		"Uroginecología",
		"Urología",
		"Urología Infantil"		
	};

	public static String[] getEspecilidades() {
		return especilidades;
	}

	public static void setEspecilidades(String[] especilidades) {
		EspecialidadesUtil.especilidades = especilidades;
	}
	
}
